In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

from sklearn.linear_model import LinearRegression

In [6]:
data = pd.read_csv('1.02. Multiple linear regression.csv')
data.head()

SAT   GPA  Rand 1,2,3
0  1714  2.40           1
1  1664  2.52           3
2  1760  2.54           3
3  1685  2.74           3
4  1693  2.83           2

In [8]:
data.describe()

SAT        GPA  Rand 1,2,3
count    84.000000  84.000000   84.000000
mean   1845.273810   3.330238    2.059524
std     104.530661   0.271617    0.855192
min    1634.000000   2.400000    1.000000
25%    1772.000000   3.190000    1.000000
50%    1846.000000   3.380000    2.000000
75%    1934.000000   3.502500    3.000000
max    2050.000000   3.810000    3.000000

In [10]:
x = data[['SAT', 'Rand 1,2,3']]
y = data['GPA']

In [12]:
reg = LinearRegression()
reg.fit(x,y)

LinearRegression()

In [14]:
reg.coef_

array([ 0.00165354, -0.00826982])

In [16]:
reg.intercept_

0.29603261264909575

In [18]:
reg.score(x,y)

0.4066811952814282

In [20]:
#Adjusted R-squared 구하는 방법?
#latech code로 수학공식 사용하기

# Formula for Adjusted R^2

$R^2_{adj.} = 1 - (1-R^2)*\frac{n-1}{n-p-1}$

In [25]:
#n = the number of observations
#p = the number of predictors

In [28]:
x.shape

(84, 2)

In [45]:
r2 = reg.score(x,y)

n = x.shape[0]
#n=84지만 x.shape 형태로 parameterize 해줌
p = x.shape[1]
#p=2지만 x.shape 형태로 parameterize 해줌

adjusted_r2 = 1-(1-r2)*(n-1)/(n-p-1)
adjusted_r2

0.39203134825134

# Feature Selection

In [33]:
from sklearn.feature_selection import f_regression

In [35]:
f_regression(x,y)

(array([56.04804786,  0.17558437]), array([7.19951844e-11, 6.76291372e-01]))

In [39]:
p_values = f_regression(x,y)[1]
p_values

array([7.19951844e-11, 6.76291372e-01])

In [41]:
p_values.round(3)

array([0.   , 0.676])

In [51]:
#reg_summary = pd.DataFrame(data=['SAT', 'Rand 1,2,3'], columns=['Features'])를 parameterize
#이게 왜 필요하지? 나중에 변수가 n개가 되었을 때 편리성을 위해서!
reg_summary = pd.DataFrame(data=x.columns.values, columns=['Features'])
reg_summary

Features
0         SAT
1  Rand 1,2,3

In [53]:
reg_summary['Coefficients'] = reg.coef_
reg_summary['p-values'] = p_values.round(3)

In [55]:
reg_summary

Features  Coefficients  p-values
0         SAT      0.001654     0.000
1  Rand 1,2,3     -0.008270     0.676

In [57]:
from sklearn.preprocessing import StandardScaler

In [67]:
scaler = StandardScaler()
#we have created an empty StandScaler object
#'scaler' will be used to subtract the mean and divide by the standard deviation

In [69]:
scaler.fit(x)

StandardScaler()

In [75]:
#Scaling Mechanisms
##StandardScaler(copy=Trye, with_mean=True, with_std=True)
##'fit' calculates and stores the mean and standard deviation of each feature
##scaler contains all standardization information

In [77]:
x_scaled = scaler.transform(x)

In [79]:
x_scaled

array([[-1.26338288, -1.24637147],
       [-1.74458431,  1.10632974],
       [-0.82067757,  1.10632974],
       [-1.54247971,  1.10632974],
       [-1.46548748, -0.07002087],
       [-1.68684014, -1.24637147],
       [-0.78218146, -0.07002087],
       [-0.78218146, -1.24637147],
       [-0.51270866, -0.07002087],
       [ 0.04548499,  1.10632974],
       [-1.06127829,  1.10632974],
       [-0.67631715, -0.07002087],
       [-1.06127829, -1.24637147],
       [-1.28263094,  1.10632974],
       [-0.6955652 , -0.07002087],
       [ 0.25721362, -0.07002087],
       [-0.86879772,  1.10632974],
       [-1.64834403, -0.07002087],
       [-0.03150724,  1.10632974],
       [-0.57045283,  1.10632974],
       [-0.81105355,  1.10632974],
       [-1.18639066,  1.10632974],
       [-1.75420834,  1.10632974],
       [-1.52323165, -1.24637147],
       [ 1.23886453, -1.24637147],
       [-0.18549169, -1.24637147],
       [-0.5608288 , -1.24637147],
       [-0.23361183,  1.10632974],
       [ 1.68156984,

# Regression with scalred features

In [84]:
reg = LinearRegression()
reg.fit(x_scaled, y)

LinearRegression()

In [86]:
reg.coef_

array([ 0.17181389, -0.00703007])

In [88]:
reg.intercept_

3.330238095238095

In [142]:
reg_summary = pd.DataFrame([['Intercept'],['SAT'],['Rand 1,2,3']], columns=['Features'])
reg_summary['Weights'] = reg.intercept_, reg.coef_[0], reg.coef_[1]

In [144]:
reg_summary

Features   Weights
0   Intercept  3.330238
1         SAT  0.171814
2  Rand 1,2,3 -0.007030

In [146]:
reg_summary = pd.DataFrame([['Bias'],['SAT'],['Rand 1,2,3']], columns=['Features'])
reg_summary['Weights'] = reg.intercept_, reg.coef_[0], reg.coef_[1]
#machine learning 용어들로 바꿔줘서('intercept'-> 'Bias' convenient summary table과 new one을 구분함

In [148]:
reg_summary

Features   Weights
0        Bias  3.330238
1         SAT  0.171814
2  Rand 1,2,3 -0.007030

# Making predictions with the standardized coefficients(weights)

In [150]:
new_data = pd.DataFrame(data=[[1700,2],[1800,1]], columns=['SAT','Rand 1,2,3'])
new_data
#feature name 띄어쓰기 주의할 것

SAT  Rand 1,2,3
0  1700           2
1  1800           1

In [152]:
reg.predict(new_data)

/opt/anaconda3/lib/python3.12/site-packages/sklearn/base.py:486: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(


array([295.39979563, 312.58821497])

In [154]:
#our model expects values that are of the same magnitude

#The new data frame should be arranged in the same way and also must be standardized in the same way

In [156]:
new_data_scaled = scaler.transform(new_data)
new_data_scaled

array([[-1.39811928, -0.07002087],
       [-0.43571643, -1.24637147]])

In [158]:
reg.predict(new_data_scaled)

array([3.09051403, 3.26413803])

# What if we removed the 'Random 1,2,3' variable?

In [187]:
reg_simple = LinearRegression()
x_simple_matrix = x_scaled[:,0]
reg_simple.fit(x_simple_matrix,y)

ValueError: Expected 2D array, got 1D array instead:
array=[-1.26338288 -1.74458431 -0.82067757 -1.54247971 -1.46548748 -1.68684014
 -0.78218146 -0.78218146 -0.51270866  0.04548499 -1.06127829 -0.67631715
 -1.06127829 -1.28263094 -0.6955652   0.25721362 -0.86879772 -1.64834403
 -0.03150724 -0.57045283 -0.81105355 -1.18639066 -1.75420834 -1.52323165
  1.23886453 -0.18549169 -0.5608288  -0.23361183  1.68156984 -0.4934606
 -0.73406132  0.85390339 -0.67631715  0.09360513  0.33420585  0.03586096
 -0.35872421  1.04638396 -0.65706909 -0.13737155  0.18984542  0.04548499
  1.1618723  -1.37887123  1.39284898  0.76728713 -0.20473975  1.06563201
  0.11285319  1.28698467 -0.41646838  0.09360513  0.59405462 -2.03330517
  0.32458182  0.40157405 -1.10939843  1.03675993 -0.61857297  0.44007016
  1.14262424 -0.35872421  0.45931822  1.88367444  0.45931822 -0.12774752
  0.04548499  0.85390339  0.15134931  0.8250313   0.84427936 -0.64744506
  1.24848856  0.85390339  1.69119387  1.6334497   1.46021718  1.68156984
 -0.02188321  0.87315144 -0.33947615  1.3639769   1.12337618  1.97029069].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [191]:
#matrix 입력값이 아니므로 reshape 필요
x_simple_matrix = x_scaled[:,0].reshape(-1,1)

In [193]:
reg_simple.fit(x_simple_matrix,y)

LinearRegression()

In [199]:
reg_simple.predict(new_data_scaled[:,0].reshape(-1,1))

array([3.08970998, 3.25527879])

In [201]:
#feature scaling해도 최종 결과에 큰 영향 없음(반올림 시 거의 동일값)
#이것이 개발자들에게 p-value가 불필요하다고 여겨지는 이유임(결과에 영향을 미치지 않으니까)
#The weights are close to 0 that they will barely influence the predictions!