# Train Test Split

## Import the relevant libraries

In [14]:
import numpy as np
from sklearn.model_selection import train_test_split

## Generate some data we are going to split

In [19]:
a = np.arange(1,101)

In [21]:
a

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [23]:
b = np.arange(501,601)
b

array([501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 512, 513,
       514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525, 526,
       527, 528, 529, 530, 531, 532, 533, 534, 535, 536, 537, 538, 539,
       540, 541, 542, 543, 544, 545, 546, 547, 548, 549, 550, 551, 552,
       553, 554, 555, 556, 557, 558, 559, 560, 561, 562, 563, 564, 565,
       566, 567, 568, 569, 570, 571, 572, 573, 574, 575, 576, 577, 578,
       579, 580, 581, 582, 583, 584, 585, 586, 587, 588, 589, 590, 591,
       592, 593, 594, 595, 596, 597, 598, 599, 600])

## Split the data

In [32]:
train_test_split(a)

[array([ 20,  98,  13,  54,  64,  96,  55,  62,  18,  61,   5,  82, 100,
         73,  86,  30,  99,  40,  14,  70,   4,   3,  75,  77,  34,  47,
         94,   6,  59,  72,  95,  50,  38,  41,  83,  21,  65,  46,  91,
         71,  23,  51,  27,  33,  52,  85,  44,  93,  79,   2,  43,  28,
         68,  17,  26,   1,  89,   9,  57,  81,  10,  60,  92,  66,  19,
         67,   7,  97,  12,  22,  25,  87,  37,  32,  53]),
 array([11, 15, 36, 58, 76, 49, 29, 24, 48, 69, 74, 80, 84, 88, 45, 56, 39,
        31, 16,  8, 78, 90, 35, 42, 63])]

In [34]:
a_train, a_test = train_test_split(a)

## Explore the result

In [36]:
a_train.shape, a_test.shape

((75,), (25,))

In [38]:
a_train

array([ 56,  46,  73,  12,  66,  70,  60,  15,  37,  40,  98,  24,  74,
        42,  59,  14,  85,  87,  26,  30,  83,  28,  77,  18,  86,  21,
        81,  47,  45,  55,  54, 100,  20,   9,  84,  51,  57,   4,  78,
        64,   3,  48,  82,  35,  90,  19,  69,  94,  80,  36,  17,  32,
        10,   6,  50,  41,  11,  13,  71,  43,  65,  61,  44,  31,  63,
        67,  96,  95,  79,   1,  39,  58,   2,  53,  34])

In [40]:
a_test

array([52, 62, 97, 22, 88, 72, 33, 27, 29, 89, 91, 99,  8, 75, 38, 49,  5,
       92, 93, 25, 76, 16,  7, 23, 68])

In [42]:
#If ((75,), (25,)) 이 내 업무에 맞지 않을 때
#If I do not like dedicating so much of my data to testing, 0과 1사이 비율값으로 test_size 입력

In [56]:
a_train, a_test = train_test_split(a, test_size=0.2)
a_train.shape, a_test.shape

((80,), (20,))

In [58]:
#time series data 와 같이 order대로 분석하는 것이 중요한 데이터의 경우
#randomly shuffled 없이 데이터 나누기, shuffle=False 입력

In [60]:
a_train, a_test = train_test_split(a, test_size=0.2, shuffle=False)
a_train

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80])

In [62]:
a_test

array([ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93,
        94,  95,  96,  97,  98,  99, 100])

In [64]:
a_train, a_test = train_test_split(a, test_size=0.2)

In [66]:
a_train

array([ 45,  37,  32,  55,  66,  33,  78,  52,  31,  84,  28,  12,  23,
        30,  54,   5,  60,  68,  82,  91,  46,  11,   8,  44,  70,  57,
        75,  51,  99,  43,  73,  25,  85,  86,  41,  79,   1,  88,  71,
        65,  39,  18,  20,  34,  69,  59,  24,  89,  58,  81,  61,  87,
        10,  50,  63,  94,  49,  53,  38,  62,  96,  40,  98,  77, 100,
         9,  93,  92,   4,  26,  16,   2,  67,  19,  22,  13,  72,  14,
        17,  27])

In [68]:
a_test

array([90, 76, 29, 35, 47, 97, 56,  6, 80, 95, 42,  7, 15, 48, 21, 64, 36,
        3, 83, 74])

In [ ]:
#random_state 에 인수를 입력하면, randomize하지만 코드 돌릴 때마다 셔플이 바뀌지는 않음

In [76]:
a_train, a_test = train_test_split(a, test_size=0.2, random_state=42)
a_train

array([ 56,  89,  27,  43,  70,  16,  41,  97,  10,  73,  12,  48,  86,
        29,  94,   6,  67,  66,  36,  17,  50,  35,   8,  96,  28,  20,
        82,  26,  63,  14,  25,   4,  18,  39,   9,  79,   7,  65,  37,
        90,  57, 100,  55,  44,  51,  68,  47,  69,  62,  98,  80,  42,
        59,  49,  99,  58,  76,  33,  95,  60,  64,  85,  38,  30,   2,
        53,  22,   3,  24,  88,  92,  75,  87,  83,  21,  61,  72,  15,
        93,  52])

In [78]:
a_test

array([84, 54, 71, 46, 45, 40, 23, 81, 11,  1, 19, 31, 74, 34, 91,  5, 77,
       78, 13, 32])

In [80]:
a_train, a_test, b_train, b_test = train_test_split(a, b, test_size=0.2, random_state=365)
a_train

array([ 25,  32,  99,  73,  91,  66,   3,  59,  94,   1,   8,  15,  90,
        54,  31,  20,  77,  82,  30,  35,  95,  42,  38,   7,  11,  50,
        21,  48,   2,  17,  10,  58,  68,  43,  41,  16,  88,  72,  79,
       100,  80,  39,  24,  86,  22,  23,  62,  76,  18,  47,  55,  26,
        60,  19,  71,  64,  51,  63,  65,  28,  12,  78,  13,  44,  75,
        87,  40,   4,  29,  49,  37,  57,  27,  74,   6,  45,  92,  34,
        53,  83])

In [82]:
a_test

array([ 9, 69, 81, 56, 33, 93, 84, 61, 46, 89, 85, 67, 97,  5, 70, 36, 98,
       96, 14, 52])

In [88]:
b_train.shape, b_test.shape

((80,), (20,))

In [84]:
b_train

array([525, 532, 599, 573, 591, 566, 503, 559, 594, 501, 508, 515, 590,
       554, 531, 520, 577, 582, 530, 535, 595, 542, 538, 507, 511, 550,
       521, 548, 502, 517, 510, 558, 568, 543, 541, 516, 588, 572, 579,
       600, 580, 539, 524, 586, 522, 523, 562, 576, 518, 547, 555, 526,
       560, 519, 571, 564, 551, 563, 565, 528, 512, 578, 513, 544, 575,
       587, 540, 504, 529, 549, 537, 557, 527, 574, 506, 545, 592, 534,
       553, 583])

In [86]:
b_test

array([509, 569, 581, 556, 533, 593, 584, 561, 546, 589, 585, 567, 597,
       505, 570, 536, 598, 596, 514, 552])